// <auto-generated />
using System;
using FilmDatenBank.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmDatenBank.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("FilmDatenBank.Data.Models.Ablage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Bemerkung")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Bemerkung");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("Ort");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("Typ");

                    b.HasKey("Id");

                    b.ToTable("tAblage");
                });

            modelBuilder.Entity("FilmDatenBank.Data.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FilmDatenBank.Data.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("fid");

                    b.Property<int?>("AblageId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fAblage");

                    b.Property<DateTime>("Aufnahme")
                        .HasColumnType("TEXT")
                        .HasColumnName("faufnahme");

                    b.Property<string>("Bemerkung")
                        .HasColumnType("TEXT")
                        .HasColumnName("fbemerkung");

                    b.Property<int>("Bewertung")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fbewertung");

                    b.Property<int>("CounterAusleihen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fcausleih");

                    b.Property<string>("DiscType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("fDiscType");

                    b.Property<string>("FilmNummer")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("fFilmNummer");

                    b.Property<bool>("IstAusgeliehen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("frent");

                    b.Property<bool>("IstGesperrt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("flock");

                    b.Property<bool>("IstMarkiert")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fmark");

                    b.Property<byte[]>("Thumbnail")
                        .HasColumnType("BLOB")
                        .HasColumnName("fThumbnail");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("fname");

                    b.Property<string>("TmdbId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("fASIN");

                    b.Property<string>("Trailer")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("fTrailer");

                    b.HasKey("Id");

                    b.HasIndex("AblageId");

                    b.ToTable("tfilme");
                });

            modelBuilder.Entity("FilmDatenBank.Data.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("gid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("gname");

                    b.HasKey("Id");

                    b.ToTable("tgenre");
                });

            modelBuilder.Entity("tFilmGenre", b =>
                {
                    b.Property<int>("Film")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Genre")
                        .HasColumnType("INTEGER");

                    b.HasKey("Film", "Genre");

                    b.HasIndex("Genre");

                    b.ToTable("tFilmGenre");
                });

            modelBuilder.Entity("FilmDatenBank.Data.Models.Film", b =>
                {
                    b.HasOne("FilmDatenBank.Data.Models.Ablage", "Ablage")
                        .WithMany("Filme")
                        .HasForeignKey("AblageId");

                    b.Navigation("Ablage");
                });

            modelBuilder.Entity("tFilmGenre", b =>
                {
                    b.HasOne("FilmDatenBank.Data.Models.Film", null)
                        .WithMany()
                        .HasForeignKey("Film")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmDatenBank.Data.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("Genre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FilmDatenBank.Data.Models.Ablage", b =>
                {
                    b.Navigation("Filme");
                });
#pragma warning restore 612, 618
        }
    }
}
